### ISSUE TITLE
RHS M252 Addition

### ISSUE THREAD

**Issue by Fearmonger** [Jester2138/Arma-FDC#1]
I don't see the RHS M252 as an option. Would you be willing to add that please? Really enjoying this app, thank you!!

**Comment by Jester2138** [comment]
Absolutely. Gonna get to adding RHS within a few days.

**Comment by Fearmonger** [comment]
Oh that is awesome, thank you. One last question for you. Do you have any plans on adding an adjust fire ability? Something that could allow a spotter to call in adjustments.

**Comment by Jester2138** [comment]
I'm not sure what the point would be. The calculator is 100% guaranteed to be accurate for the target grid because math doesn't lie and any adjustment should just be putting a new target grid in. Never felt the need for a relative adjustment myself but I'm open to example scenarios where it'd be useful.

**Comment by Jester2138** [comment]
E.g. if the observer wants to adjust 50m north just input a target 50m north.

**Comment by Fearmonger** [comment]
The Vector 21 has the ability to do "Fall of shot" that's what I was thinking would be able to be used to make adjustments. Figured it would be faster that way than attempting to adjust the grid based upon where the spotter and Artillery positions are.
https://ace3.acemod.org/wiki/feature/vector.html#29-fall-of-shot

**Comment by Jester2138** [comment]
Sorry for the delay. I see what you mean. I have been playing Arma for a decade and didn't know you could do that with the Vector haha. If I have time, I may add such a feature but no promises.

**Comment by Fearmonger** [comment]
Nothing to apologize for at all. I've got about 7 years under my belt and I still learn something new everyday about this game. I appreciate you even considering the idea of implementing this feature. Thanks again for all that you've done.
