### ISSUE TITLE
Gun properties calculation procedure

### ISSUE THREAD

**Issue by ondrej-mahdalik** [Jester2138/Arma-FDC#3]
I'd like to help with adding more mortars, especially from SOG cDLC; however, I was unable to determine how the properties of guns are calculated (the ones in [Objects.kt](../blob/master/app/src/main/java/com/armaApp/armaFDC/Objects.kt)).

Would you mind sharing the procedure?

**Comment by Jester2138** [comment]
That'd be awesome. No magic. I just go in-game with ACE, get in the
gunner's position, and look at the max/min elevation from level ground
(page up/down), and even if it goes lower still using 350 as the min to
clear nearby trees/buildings, and the muzzle velocities for the main HE
rounds, which you can see by mousing over the names in the range table.

**Comment by ondrej-mahdalik** [comment]
Alright, thank you! One more question, though - what about the spread? Can I tell it from the artillery computer by aiming at a specific distance, or is there another way?

**Comment by Jester2138** [comment]
Artillery calculator. I haven't looked at this in a while so I can't
remember whether my spread was diameter or radius (I think diameter). But I
got it by inferring the divergence in meters per second of flight from the
in-game artillery calculator (which itself calculates it from config values
but it's easier for us to do it from the calculator). My code then figures
out the spread to show the user for a particular target based on flight
time.
